### PR TITLE
Make it work with GitHub Workflows v2 format

### PR DESCRIPTION
**Pull request by thom4parisot**
Sample config:

```yml
name: Deploy to production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: contention/rsync-deployments@master
        with:
          USER_AND_HOST: user@example.com
          DEST: /path/to/target
          SRC: public/
          RSYNC_OPTIONS: -avzr --delete --exclude node_modules --exclude '.git*'
        env:
          DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
```

It accepts 3 arguments:

- `USER_AND_HOST` (mandatory): remote hostname and user (_à la_ `user@host.tld`)
- `DEST` (mandatory): remote host destination path
- `SRC` (optional): blank by default (so to say, `$GITHUB_WORKSPACE/$SRC`) — useful when something has been generated in a subfolder in a previous action (eg: `_site/` or `public/` with static site generators like Jekyll or Hugo);
- `RSYNC_OPTIONS` (optional): additional options to pass to the `rsync` command;

### CODE REVIEW

**Comment by contention** [comment]
Cool - appreciate it.

This has been on my todo list for... well... forever, and I’d actually planned to look at it this weekend, so really good timing. :o)

**Comment by thom4parisot** [comment]
Cool!

I did change only the minimum, without rethinking the use of the action with the v2 syntax. GitHub droped the array-like arguments, making it difficult to use `$1` & co args.

Feel free to revisit these changes 👍 

Thanks for publishing this action in the first place!

**Comment by rchrd2** [comment]
This fork worked for me. The code in the repo did not.

**Comment by thom4parisot** [comment]
I have updated the PR with an up to date README, reworked arguments and an additional one—to select the subfolder of the Github Action Workspace; I needed this to deploy the output of a [Hugo](https://gohugo.io) website.

**Comment by KristerV** [comment]
So the new syntax is still not working? I am prolly not going to learn the old one just to use this :D

**Comment by dweidner** [comment]
Anything holding this back? Currently it is not possible to customize the source path.

**Comment by josenicomaia** [comment]
+1

**Comment by sagannotcarl** [comment]
This change worked great for me

**Comment by thom4parisot** [comment]
I moved to [`rsync-deployments-action`](https://github.com/marketplace/actions/rsync-deployments-action) that does exactly all of the above.

**Pull request closed without merging**
